import { Product, Category, Brand, Banner, Coupon, Order, Review, User, Blog } from '@/types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-women',
    name: 'Women Clothing',
    slug: 'women',
    image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=1200&auto=format&fit=crop',
    description: 'High-end haute couture, dresses, sarees, tailored blazers, and evening gowns.',
    isFeatured: true,
    subcategories: [
      { id: 'sub-sarees', name: 'Handcrafted Sarees', slug: 'sarees', categoryId: 'cat-women' },
      { id: 'sub-dresses', name: 'Luxury Gowns & Dresses', slug: 'dresses', categoryId: 'cat-women' },
      { id: 'sub-blazers', name: 'Tailored Blazers', slug: 'blazers', categoryId: 'cat-women' },
      { id: 'sub-tops', name: 'Silk Tops & Blouses', slug: 'tops', categoryId: 'cat-women' },
    ]
  },
  {
    id: 'cat-men',
    name: 'Men Collection',
    slug: 'men',
    image: 'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?q=80&w=1200&auto=format&fit=crop',
    description: 'Sharp suits, minimal trench coats, Italian linen shirts, and modern essentials.',
    isFeatured: true,
    subcategories: [
      { id: 'sub-suits', name: 'Bespoke Suits', slug: 'suits', categoryId: 'cat-men' },
      { id: 'sub-shirts', name: 'Linen & Cotton Shirts', slug: 'shirts', categoryId: 'cat-men' },
      { id: 'sub-tshirts', name: 'T-Shirts & Polos', slug: 't-shirts', categoryId: 'cat-men' },
      { id: 'sub-outerwear', name: 'Overcoats & Jackets', slug: 'outerwear', categoryId: 'cat-men' },
    ]
  },
  {
    id: 'cat-jewellery',
    name: 'Fine Jewellery',
    slug: 'jewellery',
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1200&auto=format&fit=crop',
    description: '18K Gold, diamond necklaces, artisan earrings, and signature rings.',
    isFeatured: true,
    subcategories: [
      { id: 'sub-necklaces', name: 'Necklaces & Pendants', slug: 'necklaces', categoryId: 'cat-jewellery' },
      { id: 'sub-rings', name: 'Signature Rings', slug: 'rings', categoryId: 'cat-jewellery' },
      { id: 'sub-earrings', name: 'Earrings & Ear Cuffs', slug: 'earrings', categoryId: 'cat-jewellery' },
    ]
  },
  {
    id: 'cat-accessories',
    name: 'Leather Accessories',
    slug: 'accessories',
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=1200&auto=format&fit=crop',
    description: 'Handcrafted leather bags, designer belts, and minimalist watches.',
    isFeatured: true,
    subcategories: [
      { id: 'sub-handbags', name: 'Luxury Handbags', slug: 'handbags', categoryId: 'cat-accessories' },
      { id: 'sub-watches', name: 'Timepieces & Watches', slug: 'watches', categoryId: 'cat-accessories' },
    ]
  }
];

export const INITIAL_BRANDS: Brand[] = [
  { id: 'brand-angel', name: 'Angel Privé', slug: 'angel-prive', isFeatured: true, logo: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=300' },
  { id: 'brand-zara', name: 'Zara Studio', slug: 'zara-studio', isFeatured: true, logo: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=300' },
  { id: 'brand-maison', name: 'Maison Luxe', slug: 'maison-luxe', isFeatured: true, logo: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=300' },
  { id: 'brand-aurora', name: 'Aurora Fine Jewels', slug: 'aurora-jewels', isFeatured: true, logo: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=300' },
];

export const INITIAL_BANNERS: Banner[] = [
  {
    id: 'banner-1',
    title: 'THE AUTUMN / WINTER HAUTE COUTURE',
    subtitle: 'Discover timeless elegance crafted with Italian silk & cashmeres',
    imageUrl: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?q=80&w=1920&auto=format&fit=crop',
    mobileImageUrl: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?q=80&w=800&auto=format&fit=crop',
    link: '/shop?category=women',
    category: 'HERO_SLIDER',
    position: 1,
    isActive: true,
  },
  {
    id: 'banner-2',
    title: 'AURORA 18K FINE JEWELLERY COLLECTION',
    subtitle: 'Hand-cut ethically sourced diamonds and celestial gold',
    imageUrl: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=1920&auto=format&fit=crop',
    mobileImageUrl: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=800&auto=format&fit=crop',
    link: '/shop?category=jewellery',
    category: 'HERO_SLIDER',
    position: 2,
    isActive: true,
  },
  {
    id: 'banner-3',
    title: 'THE MODERN GENTLEMAN ESSENTIALS',
    subtitle: 'Architectural cuts and Italian tailored suits for the contemporary man',
    imageUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=1920&auto=format&fit=crop',
    mobileImageUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=800&auto=format&fit=crop',
    link: '/shop?category=men',
    category: 'HERO_SLIDER',
    position: 3,
    isActive: true,
  }
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-saree-1',
    title: 'Blush Pink Hand-Embroidered Organza Silk Saree',
    slug: 'blush-pink-hand-embroidered-organza-silk-saree',
    sku: 'ANG-W-SAR-001',
    barcode: '890123456799',
    description: 'Hand-woven organza silk saree rendered in soft blush pink, adorned with zardozi borders and intricate silver thread work.',
    shortDescription: '100% Pure Organza Silk Saree with Zardozi Embroidery',
    price: 24999,
    compareAtPrice: 32999,
    costPrice: 11000,
    stock: 15,
    lowStockThreshold: 3,
    categoryId: 'cat-women',
    category: INITIAL_CATEGORIES[0],
    subcategoryId: 'sub-sarees',
    subcategory: INITIAL_CATEGORIES[0].subcategories![0],
    brandId: 'brand-angel',
    brand: INITIAL_BRANDS[0],
    status: 'PUBLISHED',
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: true,
    tags: 'saree, sarees, organza, silk, blush pink, ethnic, women',
    rating: 4.9,
    reviewCount: 29,
    colors: ['Blush Pink', 'Champagne Gold'],
    sizes: ['Free Size'],
    materials: ['Pure Organza Silk', 'Zardozi Work'],
    images: [
      { id: 'img-sar-1', url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=1000&auto=format&fit=crop', isPrimary: true, position: 1 },
      { id: 'img-sar-2', url: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?q=80&w=1000&auto=format&fit=crop', isPrimary: false, position: 2 }
    ],
    seoTitle: 'Blush Pink Organza Silk Saree | Angel Collection',
    seoDescription: 'Shop luxury hand-embroidered organza silk saree online.',
    createdAt: '2026-07-28T10:00:00Z',
  },
  {
    id: 'prod-1',
    title: 'Satin Minimalist Evening Gown',
    slug: 'satin-minimalist-evening-gown',
    sku: 'ANG-W-001',
    barcode: '890123456701',
    description: 'Sculpted from heavyweight Italian Mulberry silk satin, this evening gown features a fluid cowl neckline, a subtle side slit, and an elegant floor-sweeping train.',
    shortDescription: '100% Italian Silk Satin Evening Gown in Midnight Black',
    price: 18999,
    compareAtPrice: 24999,
    costPrice: 8500,
    stock: 12,
    lowStockThreshold: 3,
    categoryId: 'cat-women',
    category: INITIAL_CATEGORIES[0],
    subcategoryId: 'sub-dresses',
    subcategory: INITIAL_CATEGORIES[0].subcategories![1],
    brandId: 'brand-angel',
    brand: INITIAL_BRANDS[0],
    status: 'PUBLISHED',
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: true,
    tags: 'gown, gowns, silk, evening, black, minimalist',
    rating: 4.9,
    reviewCount: 38,
    colors: ['Midnight Black', 'Champagne Gold', 'Emerald Green'],
    sizes: ['XS', 'S', 'M', 'L'],
    materials: ['100% Mulberry Silk', 'Satin Finish'],
    images: [
      { id: 'img-1-1', url: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?q=80&w=1000&auto=format&fit=crop', isPrimary: true, position: 1 },
      { id: 'img-1-2', url: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?q=80&w=1000&auto=format&fit=crop', isPrimary: false, position: 2 },
    ],
    seoTitle: 'Satin Minimalist Evening Gown | Angel Collection',
    seoDescription: 'Buy luxury Mulberry silk evening gown online at Angel Collection.',
    createdAt: '2026-07-01T10:00:00Z',
  },
  {
    id: 'prod-2',
    title: 'Double-Breasted Cashmere Blazer',
    slug: 'double-breasted-cashmere-blazer',
    sku: 'ANG-W-002',
    barcode: '890123456702',
    description: 'An architectural double-breasted coat blazer cut from Mongolian virgin wool and cashmere blend. Designed with oversized horn buttons and padded sharp shoulders.',
    shortDescription: 'Tailored Wool-Cashmere Blend Blazer',
    price: 14499,
    compareAtPrice: 18999,
    costPrice: 6200,
    stock: 8,
    lowStockThreshold: 4,
    categoryId: 'cat-women',
    category: INITIAL_CATEGORIES[0],
    subcategoryId: 'sub-blazers',
    subcategory: INITIAL_CATEGORIES[0].subcategories![2],
    brandId: 'brand-zara',
    brand: INITIAL_BRANDS[1],
    status: 'PUBLISHED',
    isFeatured: true,
    isTrending: true,
    isBestSeller: false,
    isNewArrival: true,
    tags: 'blazer, blazers, wool, cashmere, camel',
    rating: 4.8,
    reviewCount: 24,
    colors: ['Oatmeal Camel', 'Charcoal Grey', 'Off White'],
    sizes: ['S', 'M', 'L', 'XL'],
    materials: ['70% Virgin Wool', '30% Cashmere'],
    images: [
      { id: 'img-2-1', url: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=1000&auto=format&fit=crop', isPrimary: true, position: 1 },
      { id: 'img-2-2', url: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?q=80&w=1000&auto=format&fit=crop', isPrimary: false, position: 2 },
    ],
    createdAt: '2026-07-05T10:00:00Z',
  },
  {
    id: 'prod-3',
    title: 'Italian Bespoke Tuxedo Suit',
    slug: 'italian-bespoke-tuxedo-suit',
    sku: 'ANG-M-001',
    barcode: '890123456703',
    description: 'Crafted in Biella, Italy, this tuxedo features satin peak lapels, Super 150s wool fabric, and hand-stitched interior silk lining for gala dinners and weddings.',
    shortDescription: 'Super 150s Italian Wool Tuxedo Suit with Silk Lapels',
    price: 29999,
    compareAtPrice: 38999,
    costPrice: 12000,
    stock: 6,
    lowStockThreshold: 2,
    categoryId: 'cat-men',
    category: INITIAL_CATEGORIES[1],
    subcategoryId: 'sub-suits',
    subcategory: INITIAL_CATEGORIES[1].subcategories![0],
    brandId: 'brand-maison',
    brand: INITIAL_BRANDS[2],
    status: 'PUBLISHED',
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: false,
    tags: 'tuxedo, suit, suits, men, luxury, wedding',
    rating: 5.0,
    reviewCount: 42,
    colors: ['Deep Obsidian Black', 'Midnight Navy'],
    sizes: ['38R', '40R', '42R', '44R'],
    materials: ['Super 150s Wool', 'Silk Satin Lapels'],
    images: [
      { id: 'img-3-1', url: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=1000&auto=format&fit=crop', isPrimary: true, position: 1 },
    ],
    createdAt: '2026-07-08T10:00:00Z',
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  { id: 'coup-1', code: 'ANGEL10', type: 'PERCENTAGE', discountValue: 10, minPurchase: 5000, timesUsed: 14, isFirstOrderOnly: false, isActive: true },
  { id: 'coup-2', code: 'LUXE5000', type: 'FLAT', discountValue: 5000, minPurchase: 25000, timesUsed: 6, isFirstOrderOnly: false, isActive: true },
];

export const INITIAL_USERS: User[] = [
  { id: 'usr-admin', name: 'Sukhii Owner', email: 'angelcollection2021@gmail.com', role: 'OWNER', isActive: true, createdAt: '2026-01-01T00:00:00Z' },
  { id: 'usr-client', name: 'Ananya Roy', email: 'ananya@example.com', role: 'CUSTOMER', isActive: true, createdAt: '2026-06-15T00:00:00Z' },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1001',
    orderNumber: 'ANG-2026-1001',
    userId: 'usr-client',
    customerName: 'Ananya Roy',
    customerEmail: 'ananya@example.com',
    customerPhone: '+91 9876543210',
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    paymentMethod: 'RAZORPAY',
    shippingAddress: {
      id: 'addr-1',
      userId: 'usr-client',
      type: 'SHIPPING',
      name: 'Ananya Roy',
      phone: '+91 9876543210',
      street: 'Flat 4B, Imperial Towers',
      city: 'Mumbai',
      state: 'Maharashtra',
      postalCode: '400005',
      country: 'India',
      isDefault: true,
    },
    subtotal: 18999,
    discount: 0,
    shippingFee: 0,
    tax: 3419.82,
    total: 18999,
    trackingNumber: 'AWB9876543210',
    carrier: 'BlueDart Express',
    items: [
      { id: 'ord-item-1', productId: 'prod-1', title: 'Satin Minimalist Evening Gown', price: 18999, quantity: 1, size: 'S', color: 'Midnight Black', image: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=400' }
    ],
    createdAt: '2026-07-20T14:30:00Z',
  }
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    productId: 'prod-1',
    userId: 'usr-1',
    userName: 'Ananya Roy',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100',
    rating: 5,
    title: 'Exquisite silk & drape!',
    comment: 'The Mulberry silk weight is magnificent. Wore it to the Royal Opera Gala in London and received non-stop compliments.',
    isVerified: true,
    status: 'APPROVED',
    createdAt: '2026-07-15T12:00:00Z',
  },
];

export const INITIAL_BLOGS: Blog[] = [
  {
    id: 'blog-1',
    title: 'The Evolution of Modern Silk Sarees in Haute Couture',
    slug: 'evolution-of-modern-silk-sarees',
    excerpt: 'Exploring how hand-woven silk organza sarees are redefining contemporary luxury galas worldwide.',
    content: 'Silk sarees have transcended traditional occasions to become focal pieces at international galas and red carpets.',
    coverImage: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=1200',
    authorName: 'Angel Editorial',
    category: 'Couture Trends',
    readTime: '5 min read',
    isPublished: true,
    publishedAt: '2026-07-15T00:00:00Z',
  }
];
